In [2]:
!git clone https://github.com/dhairya-p/bc3412-code.git
import pandas as pd

lobster = pd.read_csv("bc3412-code/data/Lobster Shell Hardness/Lobster_Data (2004-2015).csv")
microplastics = pd.read_csv("bc3412-code/data/Microplastics Concentration/Marine_Microplastics (1995-2021).csv")
oyster = pd.read_csv("bc3412-code/data/Oyster DTA/Oyster_Histopath (1995-2010).csv")

Cloning into 'bc3412-code'...
remote: Enumerating objects: 59, done.
remote: Counting objects: 100% (59/59), done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 59 (delta 14), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (59/59), 1.44 MiB | 2.43 MiB/s, done.
Resolving deltas: 100% (14/14), done.

In [3]:
  # The 'Measurement Year' or 'Sample Date' column does not exist in the microplastics DataFrame based on its description.
  # Therefore, extracting a year from microplastics is not possible with the current data.
  print("Unique Location_IDs in lobster:", lobster['Location_ID'].unique())
  print("Lobster Year Range:", lobster['Year'].min(), "-", lobster['Year'].max())
  print("Microplastics: Unable to determine year range as no 'Year' or 'Date' column was found.")

Unique Location_IDs in lobster: [ 3  5  6  7  9 11 12 13 14 15 16 17 18 19 20 21 23 24 25  4  1  2  8 10
 22]
Lobster Year Range: 2004 - 2015
Microplastics: Unable to determine year range as no 'Year' or 'Date' column was found.

In [4]:
microplastics['Year'] = pd.to_datetime(microplastics['Sample Date'], errors='coerce').dt.year
microplastics['Year'] = microplastics['Year'].fillna(-1).astype(int) # Handle potential NaT from coercion

print("Unique Location_IDs in lobster:", lobster['Location_ID'].unique())
print("Lobster Year Range:", lobster['Year'].min(), "-", lobster['Year'].max())
print("Microplastics Year Range:", microplastics['Year'].loc[microplastics['Year'] != -1].min(), "-", microplastics['Year'].loc[microplastics['Year'] != -1].max())

Unique Location_IDs in lobster: [ 3  5  6  7  9 11 12 13 14 15 16 17 18 19 20 21 23 24 25  4  1  2  8 10
 22]
Lobster Year Range: 2004 - 2015
Microplastics Year Range: 1986 - 2022

In [5]:
print("Unique values in lobster['Location']:")
print(lobster['Location'].unique())

Unique values in lobster['Location']:
['Morell/Red Head' 'Egmont Bay' 'Howards Cove' 'Georgetown'
 'Lunenburg Inside' 'Moose Harbour' 'Port Latour Inside'
 'Port Latour Outside' 'Sambro' 'Bay of Fundy' 'Cape Sable Island Inside'
 'Cape Sable Island Outside' 'German Bank' 'Jaquards Ridge' 'Lobster Bay'
 'St Marys Bay' 'Yarmouth Inside' 'Yarmouth Outside' 'Digby' 'Borden'
 'Malpeque Bay Inside' 'Malpeque Bay Outside' 'Pinette'
 'Lunenburg Outside' 'Trinity Ledge']

In [6]:
print("Unique values in microplastics['Region']:")
print(microplastics['Region'].unique())
print("\nUnique values in microplastics['State']:")
print(microplastics['State'].unique())
print("\nUnique values in microplastics['Beach Location']:")
print(microplastics['Beach Location'].unique())

Unique values in microplastics['Region']:
[nan 'Stellwagen Bank National Marine Sanctuary' 'New York Bight'
 'Gulf of St. Lawrence' 'Bay of Fundy']

Unique values in microplastics['State']:
[nan 'Maine' 'New York' 'Rhode Island' 'New Jersey' 'Connecticut'
 'Massachusetts' 'New Hampshire']

Unique values in microplastics['Beach Location']:
[nan 'Kennebunkport beach' 'Bay Park - East Rockaway Channel'
 'Fundy Discovery Site Truly, Nova Scotia'
 'South Shore Beach, Little Compton, RI' 'East Cove Island Beach'
 'Ausable Point Campground' 'Rainbow haven beach' 'Nelson Beach'
 'White Horse Beach' 'Onset Beach' 'Laudholm Beach' 'Brant Rock Beach'
 'Long Beach' "Parker's River Beach" 'Alhambra Cove' 'Kingston Point Park'
 'Lido Beach' '5th ave Beach in Bradley Beach, NJ'
 'Ocean Park Beach in Bradley Beach, NJ'
 'Lareine Ave Beach, Bradley Beach, NJ' 'Long Point Beach'
 'Chase Way Beach' 'T-wharf South' 'T-wharf North'
 'Brinley Ave beach in Bradley Beach, NJ near the jetty.'
 'Park Place Ave beach' '4th Ave beach in Bradley Beach NJ' 'Shy Sea'
 'Walnut Beach' 'Seal Rock Road Beach' 'T Wharf South' 'T Wharf North'
 'Chaseway Beach' 'T-Wharf South' 'T-Wharf North' 'Chase Way'
 'Chase way Beach' 'Portland, Maine in harbor' 'Hampton Beach'
 'Bristol Narrows beach' 'T Warf - North' 'T Warf - South' 'BoldPt'
 'CrescentPark' 'FieldsPt' 'Wickford Harbor' 'Quonset'
 'NarragansettTownBeach' 'RockyPt' 'SandyPt' 'WeaverCove']

In [7]:
lobster_locations = lobster[['Location_ID', 'Location']].drop_duplicates().sort_values(by='Location_ID').reset_index(drop=True)
print("Unique Location_ID and Location pairs in lobster dataset:")
display(lobster_locations.head(10))

Unique Location_ID and Location pairs in lobster dataset:

   Location_ID              Location
0            1   Malpeque Bay Inside
1            2  Malpeque Bay Outside
2            3       Morell/Red Head
3            4                Borden
4            5            Egmont Bay
5            6          Howards Cove
6            7            Georgetown
7            8               Pinette
8            9      Lunenburg Inside
9           10     Lunenburg Outside

In [8]:
bay_of_fundy_coords = microplastics[microplastics['Region'] == 'Bay of Fundy'][['Latitude (degree)', 'Longitude (degree)']].mean()
gulf_st_lawrence_coords = microplastics[microplastics['Region'] == 'Gulf of St. Lawrence'][['Latitude (degree)', 'Longitude (degree)']].mean()

print("Mean coordinates for Bay of Fundy:")
print(bay_of_fundy_coords)
print("\nMean coordinates for Gulf of St. Lawrence:")
print(gulf_st_lawrence_coords)

Mean coordinates for Bay of Fundy:
Latitude (degree)     45.3714
Longitude (degree)   -63.3226
dtype: float64

Mean coordinates for Gulf of St. Lawrence:
Latitude (degree)     47.105377
Longitude (degree)   -61.386536
dtype: float64

In [9]:
import numpy as np

# 1. Initialize new columns named Latitude and Longitude in the lobster_locations DataFrame with NaN values.
lobster_locations['Latitude'] = np.nan
lobster_locations['Longitude'] = np.nan

# 2. For the row in lobster_locations where the 'Location' is 'Bay of Fundy', assign the Latitude (degree) and Longitude (degree) from the bay_of_fundy_coords Series.
lobster_locations.loc[lobster_locations['Location'] == 'Bay of Fundy', 'Latitude'] = bay_of_fundy_coords['Latitude (degree)']
lobster_locations.loc[lobster_locations['Location'] == 'Bay of Fundy', 'Longitude'] = bay_of_fundy_coords['Longitude (degree)']

# 3. Identify the lobster locations that are geographically located within the Gulf of St. Lawrence region. Specifically, for 'Malpeque Bay Inside', 'Malpeque Bay Outside', 'Morell/Red Head', 'Borden', 'Egmont Bay', 'Howards Cove', 'Georgetown', and 'Pinette', assign the Latitude (degree) and Longitude (degree) from the gulf_st_lawrence_coords Series.
gulf_st_lawrence_lobster_locations = [
    'Malpeque Bay Inside', 'Malpeque Bay Outside', 'Morell/Red Head', 'Borden',
    'Egmont Bay', 'Howards Cove', 'Georgetown', 'Pinette'
]
lobster_locations.loc[lobster_locations['Location'].isin(gulf_st_lawrence_lobster_locations), 'Latitude'] = gulf_st_lawrence_coords['Latitude (degree)']
lobster_locations.loc[lobster_locations['Location'].isin(gulf_st_lawrence_lobster_locations), 'Longitude'] = gulf_st_lawrence_coords['Longitude (degree)']

# 4. Display the updated lobster_locations DataFrame, showing the assigned coordinates and identifying any remaining unmapped locations.
print("Updated lobster_locations with assigned coordinates:")
display(lobster_locations.head(20))

Updated lobster_locations with assigned coordinates:

    Location_ID                   Location   Latitude  Longitude
0             1        Malpeque Bay Inside  47.105377 -61.386536
1             2       Malpeque Bay Outside  47.105377 -61.386536
2             3            Morell/Red Head  47.105377 -61.386536
3             4                     Borden  47.105377 -61.386536
4             5                 Egmont Bay  47.105377 -61.386536
5             6               Howards Cove  47.105377 -61.386536
6             7                 Georgetown  47.105377 -61.386536
7             8                    Pinette  47.105377 -61.386536
8             9           Lunenburg Inside        NaN        NaN
9            10          Lunenburg Outside        NaN        NaN
10           11              Moose Harbour        NaN        NaN
11           12         Port Latour Inside        NaN        NaN
12           13        Port Latour Outside        NaN        NaN
13           14                     Sambro        NaN        NaN
14           15               Bay of Fundy  45.371400 -63.322600
15           16   Cape Sable Island Inside        NaN        NaN
16           17  Cape Sable Island Outside        NaN        NaN
17           18                German Bank        NaN        NaN
18           19             Jaquards Ridge        NaN        NaN
19           20                Lobster Bay        NaN        NaN

In [12]:
from math import radians, sin, cos, sqrt, atan2

def haversine_distance(lat1, lon1, lat2, lon2):
    R = 6371  # Radius of Earth in kilometers

    lat1, lon1, lat2, lon2 = map(radians, [lat1, lon1, lat2, lon2])

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

# Initialize an empty list to store the aggregated microplastics data
aggregated_microplastics_data = []

print("Haversine distance function defined and aggregated_microplastics_data list initialized.")

Haversine distance function defined and aggregated_microplastics_data list initialized.

In [13]:
radius_km = 200 # Increased radius to capture more data

unified_years = microplastics.loc[microplastics['Year'] != -1, 'Year'].unique()

# Clear the list before re-populating to avoid appending to old data
aggregated_microplastics_data = []

for idx, lobster_loc_row in lobster_locations.iterrows():
    lobster_location_id = lobster_loc_row['Location_ID']
    lobster_location_name = lobster_loc_row['Location']
    lobster_lat = lobster_loc_row['Latitude']
    lobster_lon = lobster_loc_row['Longitude']

    # Skip if lobster location coordinates are NaN (unmapped)
    if pd.isna(lobster_lat) or pd.isna(lobster_lon):
        continue

    for year in unified_years:
        microplastics_yearly = microplastics[(microplastics['Year'] == year) &
                                             (~microplastics['Latitude (degree)'].isna()) &
                                             (~microplastics['Longitude (degree)'].isna())].copy()

        if not microplastics_yearly.empty:
            # Calculate distances
            microplastics_yearly['distance'] = microplastics_yearly.apply(
                lambda row: haversine_distance(lobster_lat, lobster_lon, row['Latitude (degree)'], row['Longitude (degree)']),
                axis=1
            )

            # Filter microplastics samples within the defined radius
            nearby_microplastics = microplastics_yearly[microplastics_yearly['distance'] <= radius_km]

            if not nearby_microplastics.empty:
                avg_concentration = nearby_microplastics['Microplastics Measurement'].mean()
            else:
                avg_concentration = np.nan # No samples within radius
        else:
            avg_concentration = np.nan # No microplastic data for that year

        # Append the aggregated data
        aggregated_microplastics_data.append({
            'Location_ID': lobster_location_id,
            'Location': lobster_location_name,
            'Year': year,
            'Latitude': lobster_lat,
            'Longitude': lobster_lon,
            'Aggregated_Microplastics_Concentration': avg_concentration
        })

# Convert the list of dictionaries into a new pandas DataFrame
aggregated_microplastics_df = pd.DataFrame(aggregated_microplastics_data)

# Display the first few rows of the resulting aggregated microplastics DataFrame
print("Aggregated Microplastics Data:")
display(aggregated_microplastics_df.head())
print(f"Number of non-null microplastic concentrations: {aggregated_microplastics_df['Aggregated_Microplastics_Concentration'].count()}")

Aggregated Microplastics Data:

,Location_ID,Location,Year,Latitude,Longitude,Aggregated_Microplastics_Concentration
0,1,Malpeque Bay Inside,1989,47.105377,-61.386536,NaN
1,1,Malpeque Bay Inside,1990,47.105377,-61.386536,NaN
2,1,Malpeque Bay Inside,1991,47.105377,-61.386536,NaN
3,1,Malpeque Bay Inside,1992,47.105377,-61.386536,NaN
4,1,Malpeque Bay Inside,1993,47.105377,-61.386536,NaN

Number of non-null microplastic concentrations: 32

In [14]:
merged_lobster_coords = pd.merge(lobster, lobster_locations[['Location_ID', 'Latitude', 'Longitude']], on='Location_ID', how='left')

final_merged_df = pd.merge(merged_lobster_coords, aggregated_microplastics_df[['Location_ID', 'Year', 'Aggregated_Microplastics_Concentration']],
                           on=['Location_ID', 'Year'], how='left')

print("Final Merged DataFrame Head:")
display(final_merged_df.head())

print("\nFinal Merged DataFrame Info:")
final_merged_df.info()

Final Merged DataFrame Head:

,Sample_ID,Date,Month,Year,LFA,Sampling_event,Location,Location_ID,Sex,Size,Min_legal_size,Season,Moultstage,Moultstage_group,Brix_st,Shellhardness,Water_depth_m,Latitude,Longitude,Aggregated_Microplastics_Concentration
0,90541,15/06/2010,6,2010,24,560,Morell/Red Head,3,1.0,99.0,73.0,1,0.0,1.0,9.3,1,NaN,47.105377,-61.386536,NaN
1,63414,04/09/2008,9,2008,25,141,Egmont Bay,5,1.0,75.0,77.0,1,0.0,1.0,6.8,1,7.08,47.105377,-61.386536,NaN
2,64215,17/09/2008,9,2008,25,658,Egmont Bay,5,1.0,76.0,77.0,1,0.0,1.0,6.1,1,7.08,47.105377,-61.386536,NaN
3,64216,17/09/2008,9,2008,25,658,Egmont Bay,5,1.0,78.0,77.0,1,0.0,1.0,8.2,1,7.08,47.105377,-61.386536,NaN
4,63412,04/09/2008,9,2008,25,141,Egmont Bay,5,1.0,80.0,77.0,1,0.0,1.0,6.6,1,7.08,47.105377,-61.386536,NaN

Final Merged DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141659 entries, 0 to 141658
Data columns (total 20 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   Sample_ID                               141659 non-null  int64
 1   Date                                    141659 non-null  object
 2   Month                                   141659 non-null  int64
 3   Year                                    141659 non-null  int64
 4   LFA                                     141659 non-null  object
 5   Sampling_event                          141659 non-null  int64
 6   Location                                141659 non-null  object
 7   Location_ID                             141659 non-null  int64
 8   Sex                                     141639 non-null  float64
 9   Size                                    141644 non-null  float64
 10  Min_legal_size                          141659 non-null  float64
 11  Season                                  141659 non-null  int64
 12  Moultstage                              141485 non-null  float64
 13  Moultstage_group                        141485 non-null  float64
 14  Brix_st                                 140767 non-null  float64
 15  Shellhardness                           141659 non-null  int64
 16  Water_depth_m                           114129 non-null  float64
 17  Latitude                                15785 non-null   float64
 18  Longitude                               15785 non-null   float64
 19  Aggregated_Microplastics_Concentration  53 non-null      float64
dtypes: float64(10), int64(7), object(3)
memory usage: 21.6+ MB

In [15]:
valid_aggregated_mp = aggregated_microplastics_df[aggregated_microplastics_df['Aggregated_Microplastics_Concentration'].notna()].copy()

print("Valid Aggregated Microplastics Data (head):")
display(valid_aggregated_mp.head())
print(f"Number of non-null microplastic concentrations in valid_aggregated_mp: {valid_aggregated_mp['Aggregated_Microplastics_Concentration'].count()}")

Valid Aggregated Microplastics Data (head):

,Location_ID,Location,Year,Latitude,Longitude,Aggregated_Microplastics_Concentration
12,1,Malpeque Bay Inside,2001,47.105377,-61.386536,0.0000
24,1,Malpeque Bay Inside,2015,47.105377,-61.386536,0.0015
43,2,Malpeque Bay Outside,2001,47.105377,-61.386536,0.0000
55,2,Malpeque Bay Outside,2015,47.105377,-61.386536,0.0015
74,3,Morell/Red Head,2001,47.105377,-61.386536,0.0000

Number of non-null microplastic concentrations in valid_aggregated_mp: 32

In [16]:
mp_valid_id_year_pairs = set(valid_aggregated_mp[['Location_ID', 'Year']].itertuples(index=False, name=None))

print(f"Number of unique (Location_ID, Year) pairs in valid_aggregated_mp: {len(mp_valid_id_year_pairs)}")

Number of unique (Location_ID, Year) pairs in valid_aggregated_mp: 32

In [17]:
regression_df = final_merged_df[['Shellhardness', 'Aggregated_Microplastics_Concentration']].dropna()

print(f"Shape of regression data after dropping NaNs: {regression_df.shape}")
display(regression_df.head())

Shape of regression data after dropping NaNs: (53, 2)

       Shellhardness  Aggregated_Microplastics_Concentration
1178               1                                0.031677
6922               2                                0.031677
6957               2                                0.031677
7034               2                                0.031677
15957              2                                0.031677

In [18]:
import statsmodels.api as sm

X = regression_df['Aggregated_Microplastics_Concentration']
Y = regression_df['Shellhardness']

X = sm.add_constant(X) # Adds a constant term to the predictor

model = sm.OLS(Y, X).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          Shellhardness   R-squared:                      -0.000
Model:                            OLS   Adj. R-squared:                 -0.000
Method:                 Least Squares   F-statistic:                       nan
Date:                Thu, 26 Mar 2026   Prob (F-statistic):                nan
Time:                        13:55:57   Log-Likelihood:                -29.571
No. Observations:                  53   AIC:                             61.14
Df Residuals:                      52   BIC:                             63.11
Df Model:                           0
Covariance Type:            nonrobust
==========================================================================================================
                                             coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
Aggregated_Microplastics_Concentration    89.3443      1.851     48.277      0.000      85.631      93.058
==============================================================================
Omnibus:                       43.730   Durbin-Watson:                   0.422
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              123.786
Skew:                          -2.476   Prob(JB):                     1.32e-27
Kurtosis:                       8.615   Cond. No.                         1.00
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

The regression results above show the statistical relationship between `Aggregated_Microplastics_Concentration` and `Shellhardness`. Key metrics to look at include:

*   **R-squared:** Indicates the proportion of the variance in the dependent variable (`Shellhardness`) that is predictable from the independent variable (`Aggregated_Microplastics_Concentration`).
*   **P-value for 'Aggregated_Microplastics_Concentration':** This tells us if the microplastic concentration is a statistically significant predictor of shell hardness. A p-value less than 0.05 typically indicates significance.
*   **Coeff (coefficient) for 'Aggregated_Microplastics_Concentration':** This is the estimated change in `Shellhardness` for every one-unit increase in `Aggregated_Microplastics_Concentration`.